cp ../BprimeAnalysis/res/JetHT_runB_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runB_cat0_singleH_q2Down.root 
cp ../BprimeAnalysis/res/JetHT_runB_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runB_cat0_singleH_q2Up.root 
cp ../BprimeAnalysis/res/JetHT_runC_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runC_cat0_singleH_q2Down.root
cp ../BprimeAnalysis/res/JetHT_runC_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runC_cat0_singleH_q2Up.root
cp ../BprimeAnalysis/res/JetHT_runD_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runD_cat0_singleH_q2Down.root
cp ../BprimeAnalysis/res/JetHT_runD_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runD_cat0_singleH_q2Up.root
cp ../BprimeAnalysis/res/JetHT_runE_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runE_cat0_singleH_q2Down.root
cp ../BprimeAnalysis/res/JetHT_runE_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runE_cat0_singleH_q2Up.root
cp ../BprimeAnalysis/res/JetHT_runF_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runF_cat0_singleH_q2Down.root
cp ../BprimeAnalysis/res/JetHT_runF_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runF_cat0_singleH_q2Up.root
cp ../BprimeAnalysis/res/JetHT_runG_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runG_cat0_singleH_q2Down.root
cp ../BprimeAnalysis/res/JetHT_runG_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runG_cat0_singleH_q2Up.root
cp ../BprimeAnalysis/res/JetHT_runHv2_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runHv2_cat0_singleH_q2Down.root
cp ../BprimeAnalysis/res/JetHT_runHv2_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runHv2_cat0_singleH_q2Up.root
cp ../BprimeAnalysis/res/JetHT_runHv3_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runHv3_cat0_singleH_q2Down.root
cp ../BprimeAnalysis/res/JetHT_runHv3_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runHv3_cat0_singleH_q2Up.root
cp ../BprimeAnalysis/res/JetHT_runB_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runB_cat0_singleH_pdf_totalDown.root
cp ../BprimeAnalysis/res/JetHT_runB_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runB_cat0_singleH_pdf_totalUp.root
cp ../BprimeAnalysis/res/JetHT_runC_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runC_cat0_singleH_pdf_totalDown.root
cp ../BprimeAnalysis/res/JetHT_runC_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runC_cat0_singleH_pdf_totalUp.root
cp ../BprimeAnalysis/res/JetHT_runD_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runD_cat0_singleH_pdf_totalDown.root
cp ../BprimeAnalysis/res/JetHT_runD_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runD_cat0_singleH_pdf_totalUp.root
cp ../BprimeAnalysis/res/JetHT_runE_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runE_cat0_singleH_pdf_totalDown.root
cp ../BprimeAnalysis/res/JetHT_runE_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runE_cat0_singleH_pdf_totalUp.root
cp ../BprimeAnalysis/res/JetHT_runF_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runF_cat0_singleH_pdf_totalDown.root
cp ../BprimeAnalysis/res/JetHT_runF_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runF_cat0_singleH_pdf_totalUp.root
cp ../BprimeAnalysis/res/JetHT_runG_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runG_cat0_singleH_pdf_totalDown.root
cp ../BprimeAnalysis/res/JetHT_runG_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runG_cat0_singleH_pdf_totalUp.root
cp ../BprimeAnalysis/res/JetHT_runHv2_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runHv2_cat0_singleH_pdf_totalDown.root
cp ../BprimeAnalysis/res/JetHT_runHv2_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runHv2_cat0_singleH_pdf_totalUp.root
cp ../BprimeAnalysis/res/JetHT_runHv3_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runHv3_cat0_singleH_pdf_totalDown.root
cp ../BprimeAnalysis/res/JetHT_runHv3_cat0_singleH.root ../BprimeAnalysis/res/JetHT_runHv3_cat0_singleH_pdf_totalUp.root     